# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}


start_step init_design
set ACTIVE_STEP init_design
set rc [catch {
  create_msg_db init_design.pb
  create_project -in_memory -part xc7a35ticsg324-1L
  set_property board_part digilentinc.com:arty:part0:1.1 [current_project]
  set_property design_mode GateLvl [current_fileset]
  set_param project.singleFileAddWarning.threshold 0
  set_property webtalk.parent_dir D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/arty_scr1/arty_scr1.cache/wt [current_project]
  set_property parent.project_path D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/arty_scr1/arty_scr1.xpr [current_project]
  set_property ip_output_repo D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/arty_scr1/arty_scr1.cache/ip [current_project]
  set_property ip_cache_permissions {read write} [current_project]
  set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
  add_files -quiet D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/arty_scr1/arty_scr1.runs/synth_1/arty_scr1_top.dcp
  set_msg_config -source 4 -id {BD 41-1661} -limit 0
  set_param project.isImplRun true
  add_files D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/system.bd
  add_files D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/sys_pll/sys_pll.bd
  read_ip -quiet D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/arty_scr1/arty_scr1.srcs/sources_1/ip/FPU_ap_faddfsub_3_full_dsp_32/FPU_ap_faddfsub_3_full_dsp_32.xci
  read_ip -quiet D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/arty_scr1/arty_scr1.srcs/sources_1/ip/FPU_ap_fcmp_0_no_dsp_32/FPU_ap_fcmp_0_no_dsp_32.xci
  read_ip -quiet D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/arty_scr1/arty_scr1.srcs/sources_1/ip/FPU_ap_fmul_2_max_dsp_32/FPU_ap_fmul_2_max_dsp_32.xci
  read_ip -quiet D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/arty_scr1/arty_scr1.srcs/sources_1/ip/FPU_ap_sitofp_4_no_dsp_32/FPU_ap_sitofp_4_no_dsp_32.xci
  read_ip -quiet d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/arty_scr1/arty_scr1.srcs/sources_1/ip/FPU_ap_faddfsub_0_full_dsp_32/FPU_ap_faddfsub_0_full_dsp_32.xci
  read_ip -quiet d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/arty_scr1/arty_scr1.srcs/sources_1/ip/FPU_ap_fmul_0_max_dsp_32/FPU_ap_fmul_0_max_dsp_32.xci
  read_ip -quiet d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/arty_scr1/arty_scr1.srcs/sources_1/ip/FPU_ap_sitofp_0_no_dsp_32/FPU_ap_sitofp_0_no_dsp_32.xci
  set_param project.isImplRun false
  read_xdc D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/constrs/arty_scr1_synth.xdc
  read_xdc D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/constrs/arty_scr1_physical.xdc
  read_xdc D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/constrs/arty_scr1_timing.xdc
  set_param project.isImplRun true
  link_design -top arty_scr1_top -part xc7a35ticsg324-1L
  set_param project.isImplRun false
  write_hwdef -force -file arty_scr1_top.hwdef
  close_msg_db -file init_design.pb
} RESULT]
if {$rc} {
  step_failed init_design
  return -code error $RESULT
} else {
  end_step init_design
  unset ACTIVE_STEP 
}

start_step opt_design
set ACTIVE_STEP opt_design
set rc [catch {
  create_msg_db opt_design.pb
  opt_design 
  write_checkpoint -force arty_scr1_top_opt.dcp
  create_report "impl_1_opt_report_drc_0" "report_drc -file arty_scr1_top_drc_opted.rpt -pb arty_scr1_top_drc_opted.pb -rpx arty_scr1_top_drc_opted.rpx"
  close_msg_db -file opt_design.pb
} RESULT]
if {$rc} {
  step_failed opt_design
  return -code error $RESULT
} else {
  end_step opt_design
  unset ACTIVE_STEP 
}

start_step place_design
set ACTIVE_STEP place_design
set rc [catch {
  create_msg_db place_design.pb
  if { [llength [get_debug_cores -quiet] ] > 0 }  { 
    implement_debug_core 
  } 
  place_design -directive WLDrivenBlockPlacement
  write_checkpoint -force arty_scr1_top_placed.dcp
  create_report "impl_1_place_report_io_0" "report_io -file arty_scr1_top_io_placed.rpt"
  create_report "impl_1_place_report_utilization_0" "report_utilization -file arty_scr1_top_utilization_placed.rpt -pb arty_scr1_top_utilization_placed.pb"
  create_report "impl_1_place_report_control_sets_0" "report_control_sets -verbose -file arty_scr1_top_control_sets_placed.rpt"
  close_msg_db -file place_design.pb
} RESULT]
if {$rc} {
  step_failed place_design
  return -code error $RESULT
} else {
  end_step place_design
  unset ACTIVE_STEP 
}

start_step post_place_power_opt_design
set ACTIVE_STEP post_place_power_opt_design
set rc [catch {
  create_msg_db post_place_power_opt_design.pb
  power_opt_design 
  write_checkpoint -force arty_scr1_top_postplace_pwropt.dcp
  close_msg_db -file post_place_power_opt_design.pb
} RESULT]
if {$rc} {
  step_failed post_place_power_opt_design
  return -code error $RESULT
} else {
  end_step post_place_power_opt_design
  unset ACTIVE_STEP 
}

start_step phys_opt_design
set ACTIVE_STEP phys_opt_design
set rc [catch {
  create_msg_db phys_opt_design.pb
  phys_opt_design -directive AggressiveExplore
  write_checkpoint -force arty_scr1_top_physopt.dcp
  close_msg_db -file phys_opt_design.pb
} RESULT]
if {$rc} {
  step_failed phys_opt_design
  return -code error $RESULT
} else {
  end_step phys_opt_design
  unset ACTIVE_STEP 
}

  set_msg_config -source 4 -id {Route 35-39} -severity "critical warning" -new_severity warning
start_step route_design
set ACTIVE_STEP route_design
set rc [catch {
  create_msg_db route_design.pb
  route_design -directive Explore
  write_checkpoint -force arty_scr1_top_routed.dcp
  create_report "impl_1_route_report_drc_0" "report_drc -file arty_scr1_top_drc_routed.rpt -pb arty_scr1_top_drc_routed.pb -rpx arty_scr1_top_drc_routed.rpx"
  create_report "impl_1_route_report_methodology_0" "report_methodology -file arty_scr1_top_methodology_drc_routed.rpt -pb arty_scr1_top_methodology_drc_routed.pb -rpx arty_scr1_top_methodology_drc_routed.rpx"
  create_report "impl_1_route_report_power_0" "report_power -file arty_scr1_top_power_routed.rpt -pb arty_scr1_top_power_summary_routed.pb -rpx arty_scr1_top_power_routed.rpx"
  create_report "impl_1_route_report_route_status_0" "report_route_status -file arty_scr1_top_route_status.rpt -pb arty_scr1_top_route_status.pb"
  create_report "impl_1_route_report_timing_summary_0" "report_timing_summary -max_paths 10 -file arty_scr1_top_timing_summary_routed.rpt -pb arty_scr1_top_timing_summary_routed.pb -rpx arty_scr1_top_timing_summary_routed.rpx"
  create_report "impl_1_route_report_incremental_reuse_0" "report_incremental_reuse -file arty_scr1_top_incremental_reuse_routed.rpt"
  create_report "impl_1_route_report_clock_utilization_0" "report_clock_utilization -file arty_scr1_top_clock_utilization_routed.rpt"
  create_report "impl_1_route_report_bus_skew_0" "report_bus_skew -warn_on_violation -file route_report_bus_skew_0.rpt -rpx route_report_bus_skew_0.rpx"
  close_msg_db -file route_design.pb
} RESULT]
if {$rc} {
  write_checkpoint -force arty_scr1_top_routed_error.dcp
  step_failed route_design
  return -code error $RESULT
} else {
  end_step route_design
  unset ACTIVE_STEP 
}

start_step post_route_phys_opt_design
set ACTIVE_STEP post_route_phys_opt_design
set rc [catch {
  create_msg_db post_route_phys_opt_design.pb
  phys_opt_design -directive AggressiveExplore
  write_checkpoint -force arty_scr1_top_postroute_physopt.dcp
  create_report "impl_1_post_route_phys_opt_report_timing_summary_0" "report_timing_summary -max_paths 10 -warn_on_violation -file arty_scr1_top_timing_summary_postroute_physopted.rpt -pb arty_scr1_top_timing_summary_postroute_physopted.pb -rpx arty_scr1_top_timing_summary_postroute_physopted.rpx"
  create_report "impl_1_post_route_phys_opt_report_bus_skew_0" "report_bus_skew -warn_on_violation -file post_route_phys_opt_report_bus_skew_0.rpt -rpx post_route_phys_opt_report_bus_skew_0.rpx"
  close_msg_db -file post_route_phys_opt_design.pb
} RESULT]
if {$rc} {
  step_failed post_route_phys_opt_design
  return -code error $RESULT
} else {
  end_step post_route_phys_opt_design
  unset ACTIVE_STEP 
}

start_step write_bitstream
set ACTIVE_STEP write_bitstream
set rc [catch {
  create_msg_db write_bitstream.pb
  set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
  catch { write_mem_info -force arty_scr1_top.mmi }
  write_bitstream -force arty_scr1_top.bit 
  catch { write_sysdef -hwdef arty_scr1_top.hwdef -bitfile arty_scr1_top.bit -meminfo arty_scr1_top.mmi -file arty_scr1_top.sysdef }
  catch {write_debug_probes -quiet -force arty_scr1_top}
  catch {file copy -force arty_scr1_top.ltx debug_nets.ltx}
  close_msg_db -file write_bitstream.pb
} RESULT]
if {$rc} {
  step_failed write_bitstream
  return -code error $RESULT
} else {
  end_step write_bitstream
  unset ACTIVE_STEP 
}

