// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="FPU,hls_ip_2018_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100tcsg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.602750,HLS_SYN_LAT=3,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=5,HLS_SYN_FF=1256,HLS_SYN_LUT=3585,HLS_VERSION=2018_2}" *)

module FPU (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        agg_result_rd_i,
        agg_result_rd_i_ap_vld,
        agg_result_rd_f,
        agg_result_rd_f_ap_vld,
        agg_result_b1,
        agg_result_b1_ap_vld,
        agg_result_f,
        agg_result_f_ap_vld,
        val_rs1,
        val_rs2,
        val_i,
        val_funct7,
        val_funct3
);

parameter    ap_ST_fsm_state1 = 27'd1;
parameter    ap_ST_fsm_state2 = 27'd2;
parameter    ap_ST_fsm_state3 = 27'd4;
parameter    ap_ST_fsm_state4 = 27'd8;
parameter    ap_ST_fsm_state5 = 27'd16;
parameter    ap_ST_fsm_state6 = 27'd32;
parameter    ap_ST_fsm_state7 = 27'd64;
parameter    ap_ST_fsm_state8 = 27'd128;
parameter    ap_ST_fsm_state9 = 27'd256;
parameter    ap_ST_fsm_state10 = 27'd512;
parameter    ap_ST_fsm_state11 = 27'd1024;
parameter    ap_ST_fsm_state12 = 27'd2048;
parameter    ap_ST_fsm_state13 = 27'd4096;
parameter    ap_ST_fsm_state14 = 27'd8192;
parameter    ap_ST_fsm_state15 = 27'd16384;
parameter    ap_ST_fsm_state16 = 27'd32768;
parameter    ap_ST_fsm_state17 = 27'd65536;
parameter    ap_ST_fsm_state18 = 27'd131072;
parameter    ap_ST_fsm_state19 = 27'd262144;
parameter    ap_ST_fsm_state20 = 27'd524288;
parameter    ap_ST_fsm_state21 = 27'd1048576;
parameter    ap_ST_fsm_state22 = 27'd2097152;
parameter    ap_ST_fsm_state23 = 27'd4194304;
parameter    ap_ST_fsm_state24 = 27'd8388608;
parameter    ap_ST_fsm_state25 = 27'd16777216;
parameter    ap_ST_fsm_state26 = 27'd33554432;
parameter    ap_ST_fsm_state27 = 27'd67108864;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] agg_result_rd_i;
output   agg_result_rd_i_ap_vld;
output  [31:0] agg_result_rd_f;
output   agg_result_rd_f_ap_vld;
output  [0:0] agg_result_b1;
output   agg_result_b1_ap_vld;
output  [0:0] agg_result_f;
output   agg_result_f_ap_vld;
input  [31:0] val_rs1;
input  [31:0] val_rs2;
input  [31:0] val_i;
input  [31:0] val_funct7;
input  [31:0] val_funct3;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg agg_result_rd_i_ap_vld;
reg agg_result_rd_f_ap_vld;
reg agg_result_b1_ap_vld;
reg agg_result_f_ap_vld;

(* fsm_encoding = "none" *) reg   [26:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] tmp_fu_332_p2;
reg   [0:0] tmp_reg_1728;
wire   [0:0] tmp_s_fu_338_p2;
reg   [0:0] tmp_s_reg_1734;
wire   [0:0] tmp_2_fu_344_p2;
reg   [0:0] tmp_2_reg_1738;
wire   [0:0] tmp_3_fu_350_p2;
reg   [0:0] tmp_3_reg_1742;
wire   [0:0] tmp_4_fu_356_p2;
reg   [0:0] tmp_4_reg_1746;
wire   [0:0] or_cond_40_fu_368_p2;
reg   [0:0] or_cond_40_reg_1750;
wire   [0:0] or_cond5_fu_374_p2;
reg   [0:0] or_cond5_reg_1754;
wire   [0:0] or_cond6_fu_386_p2;
reg   [0:0] or_cond6_reg_1758;
wire   [0:0] or_cond7_fu_392_p2;
reg   [0:0] or_cond7_reg_1762;
wire   [0:0] or_cond8_fu_398_p2;
reg   [0:0] or_cond8_reg_1766;
wire   [0:0] tmp_11_fu_404_p2;
reg   [0:0] tmp_11_reg_1770;
wire   [8:0] val_out_rd_i_4_FCLASS_fu_281_ap_return;
reg   [8:0] val_out_rd_i_4_reg_1777;
wire   [0:0] or_cond9_fu_416_p2;
wire   [0:0] or_cond_i_fu_464_p2;
reg   [0:0] or_cond_i_reg_1782;
wire   [31:0] p_Val2_38_fu_470_p1;
reg   [31:0] p_Val2_38_reg_1788;
wire   [31:0] p_Val2_37_fu_584_p3;
reg   [31:0] p_Val2_37_reg_1793;
wire   [31:0] storemerge_in_i_fu_612_p3;
reg   [31:0] storemerge_in_i_reg_1800;
wire   [0:0] sel_tmp6_i3_fu_626_p2;
reg   [0:0] sel_tmp6_i3_reg_1805;
wire   [0:0] tmp_32_fu_710_p2;
reg   [0:0] tmp_32_reg_1811;
wire   [0:0] tmp_25_fu_794_p2;
reg   [0:0] tmp_25_reg_1816;
wire   [0:0] tmp_51_i_fu_884_p2;
reg   [0:0] tmp_51_i_reg_1821;
wire   [31:0] res_13_fu_1158_p3;
reg   [31:0] res_13_reg_1826;
wire   [31:0] res_12_fu_1434_p3;
reg   [31:0] res_12_reg_1831;
wire   [0:0] val_out_f_fu_1592_p2;
wire   [31:0] val_out_rd_f_3_fu_1598_p3;
wire   [31:0] val_out_rd_i_9_trunc_fu_1606_p1;
wire    ap_CS_fsm_state2;
wire   [31:0] sel_tmp4_i_fu_1649_p3;
reg   [31:0] sel_tmp4_i_reg_1851;
wire    ap_CS_fsm_state3;
wire   [31:0] val_out_rd_i_3_fu_1657_p3;
reg   [31:0] val_out_rd_i_3_reg_1856;
wire    ap_CS_fsm_state8;
wire   [31:0] val_out_rd_f_6_fu_1663_p3;
reg   [31:0] val_out_rd_f_6_reg_1861;
wire   [31:0] val_out_rd_i_2_fu_1707_p1;
wire    ap_CS_fsm_state10;
wire   [31:0] val_out_rd_i_fu_1710_p1;
wire    ap_CS_fsm_state11;
wire   [31:0] val_out_rd_i_1_fu_1713_p1;
wire    ap_CS_fsm_state12;
wire   [31:0] grp_fu_295_p2;
wire    ap_CS_fsm_state17;
wire   [31:0] grp_fu_289_p2;
reg   [31:0] val_out_rd_f_1_reg_1886;
wire    ap_CS_fsm_state21;
reg   [31:0] val_out_rd_f_reg_1891;
wire    ap_CS_fsm_state26;
wire    val_out_rd_i_4_FCLASS_fu_281_ap_ready;
reg   [0:0] ap_phi_mux_val_out_f_8_phi_fu_169_p24;
reg   [0:0] val_out_f_8_reg_164;
wire    ap_CS_fsm_state27;
wire    ap_CS_fsm_state22;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state9;
reg   [31:0] ap_phi_mux_x_assign_phi_fu_211_p24;
reg   [31:0] x_assign_reg_207;
reg   [31:0] ap_phi_mux_val_out_rd_i_9_phi_fu_247_p24;
reg   [31:0] val_out_rd_i_9_reg_243;
reg   [31:0] grp_fu_304_p0;
reg   [31:0] grp_fu_304_p1;
reg   [31:0] grp_fu_310_p0;
reg   [31:0] grp_fu_310_p1;
wire   [0:0] tmp_5_fu_362_p2;
wire   [0:0] grp_fu_320_p2;
wire   [0:0] grp_fu_326_p2;
wire   [0:0] tmp_8_fu_380_p2;
wire   [0:0] tmp_12_fu_410_p2;
wire   [31:0] val_rs2_to_int4_fu_422_p1;
wire   [7:0] tmp_33_fu_426_p4;
wire   [22:0] tmp_59_fu_436_p1;
wire   [0:0] notrhs_fu_446_p2;
wire   [0:0] notlhs_fu_440_p2;
wire   [0:0] tmp_34_fu_452_p2;
wire   [0:0] grp_fu_304_p2;
wire   [0:0] tmp_36_fu_458_p2;
wire   [0:0] grp_fu_310_p2;
wire   [22:0] loc_V_9_fu_484_p1;
wire   [24:0] tmp_14_i_i_i_i_fu_488_p4;
wire   [7:0] loc_V_8_fu_474_p4;
wire   [8:0] tmp_i_i_i_i_i_cast_fu_502_p1;
wire   [8:0] sh_assign_fu_506_p2;
wire   [7:0] tmp_15_i_i_i_i_fu_520_p2;
wire   [0:0] isNeg_fu_512_p3;
wire  signed [8:0] tmp_15_i_i_i_i_cast_fu_526_p1;
wire  signed [8:0] sh_assign_1_fu_530_p3;
wire  signed [31:0] sh_assign_1_i_cast_fu_538_p1;
wire  signed [24:0] sh_assign_1_i_cast_c_fu_542_p1;
wire   [78:0] tmp_14_i_i_i_i_cast1_fu_498_p1;
wire   [78:0] tmp_16_i_i_i_i_fu_546_p1;
wire   [24:0] tmp_17_i_i_i_i_fu_550_p2;
wire   [0:0] tmp_62_fu_562_p3;
wire   [78:0] tmp_18_i_i_i_i_fu_556_p2;
wire   [31:0] tmp_38_fu_570_p1;
wire   [31:0] tmp_39_fu_574_p4;
wire   [0:0] abscond_i_fu_598_p2;
wire   [31:0] neg_i_fu_592_p2;
wire   [31:0] abs_i_fu_604_p3;
wire   [0:0] sel_tmp5_i_fu_620_p2;
wire   [31:0] val_rs1_to_int3_fu_632_p1;
wire   [31:0] val_rs2_to_int3_fu_650_p1;
wire   [7:0] tmp_26_fu_636_p4;
wire   [22:0] tmp_57_fu_646_p1;
wire   [0:0] notrhs7_fu_674_p2;
wire   [0:0] notlhs7_fu_668_p2;
wire   [7:0] tmp_27_fu_654_p4;
wire   [22:0] tmp_58_fu_664_p1;
wire   [0:0] notrhs8_fu_692_p2;
wire   [0:0] notlhs8_fu_686_p2;
wire   [0:0] tmp_28_fu_680_p2;
wire   [0:0] tmp_29_fu_698_p2;
wire   [0:0] tmp_30_fu_704_p2;
wire   [31:0] val_rs1_to_int2_fu_716_p1;
wire   [31:0] val_rs2_to_int2_fu_734_p1;
wire   [7:0] tmp_19_fu_720_p4;
wire   [22:0] tmp_55_fu_730_p1;
wire   [0:0] notrhs5_fu_758_p2;
wire   [0:0] notlhs5_fu_752_p2;
wire   [7:0] tmp_20_fu_738_p4;
wire   [22:0] tmp_56_fu_748_p1;
wire   [0:0] notrhs6_fu_776_p2;
wire   [0:0] notlhs6_fu_770_p2;
wire   [0:0] tmp_21_fu_764_p2;
wire   [0:0] tmp_22_fu_782_p2;
wire   [0:0] tmp_23_fu_788_p2;
wire   [31:0] val_rs1_to_int_fu_800_p1;
wire   [31:0] val_rs2_to_int_fu_818_p1;
wire   [7:0] tmp_9_fu_804_p4;
wire   [22:0] tmp_53_fu_814_p1;
wire   [0:0] notrhs1_fu_842_p2;
wire   [0:0] notlhs1_fu_836_p2;
wire   [7:0] tmp_1_fu_822_p4;
wire   [22:0] tmp_54_fu_832_p1;
wire   [0:0] notrhs2_fu_860_p2;
wire   [0:0] notlhs2_fu_854_p2;
wire   [0:0] tmp_13_fu_848_p2;
wire   [0:0] tmp_14_fu_866_p2;
wire   [0:0] tmp_15_fu_872_p2;
wire   [0:0] tmp_17_fu_878_p2;
wire   [31:0] t_V_8_fu_890_p1;
wire   [31:0] t_V_9_fu_916_p1;
wire   [7:0] loc_V_4_fu_902_p4;
wire   [22:0] loc_V_5_fu_912_p1;
wire   [7:0] loc_V_6_fu_928_p4;
wire   [22:0] loc_V_7_fu_938_p1;
wire   [0:0] tmp_i_fu_948_p2;
wire   [0:0] tmp_6_i_fu_954_p2;
wire   [0:0] tmp_i1_41_fu_942_p2;
wire   [0:0] tmp_7_i_fu_960_p2;
wire   [0:0] tmp6_fu_972_p2;
wire   [0:0] tmp5_fu_966_p2;
wire   [0:0] tmp_i_i1_fu_984_p2;
wire   [0:0] tmp_1_i_i1_fu_990_p2;
wire   [0:0] tmp_i2_i_fu_1002_p2;
wire   [0:0] tmp_1_i2_i_fu_1008_p2;
wire   [0:0] p_Result_36_fu_894_p3;
reg   [22:0] p_Result_67_fu_1020_p4;
wire   [31:0] p_Result_68_fu_1030_p4;
wire   [0:0] ymaggreater_2_fu_1044_p2;
wire   [0:0] ymaggreater_3_fu_1050_p2;
wire   [0:0] p_Result_40_fu_920_p3;
wire   [0:0] p_i1_fu_1056_p3;
wire   [0:0] ymaggreater4_i_fu_1064_p3;
wire   [0:0] or_cond4_i_fu_978_p2;
wire   [0:0] tmp_9_demorgan_i_fu_996_p2;
wire   [0:0] sel_tmp_i1_fu_1080_p2;
wire   [0:0] sel_tmp1_i1_fu_1086_p2;
wire   [0:0] tmp_11_demorgan_i_fu_1014_p2;
wire   [0:0] sel_tmp2_i1_fu_1092_p2;
wire   [31:0] res_6_fu_1040_p1;
wire   [31:0] res_7_fu_1072_p3;
wire   [0:0] sel_tmp6_i2_demorgan_fu_1106_p2;
wire   [0:0] sel_tmp6_i2_fu_1112_p2;
wire   [0:0] sel_tmp7_i1_fu_1118_p2;
wire   [31:0] res_8_fu_1098_p3;
wire   [0:0] sel_tmp11_demorgan_i_1_fu_1132_p2;
wire   [0:0] sel_tmp11_i1_fu_1138_p2;
wire   [0:0] sel_tmp12_i1_fu_1144_p2;
wire   [31:0] res_9_fu_1124_p3;
wire   [31:0] res_10_fu_1150_p3;
wire   [31:0] t_V_5_fu_1166_p1;
wire   [31:0] t_V_6_fu_1192_p1;
wire   [7:0] loc_V_fu_1178_p4;
wire   [22:0] loc_V_1_fu_1188_p1;
wire   [7:0] loc_V_2_fu_1204_p4;
wire   [22:0] loc_V_3_fu_1214_p1;
wire   [0:0] tmp_8_i_fu_1224_p2;
wire   [0:0] tmp_9_i_fu_1230_p2;
wire   [0:0] tmp_i4_fu_1218_p2;
wire   [0:0] tmp_i5_fu_1236_p2;
wire   [0:0] tmp4_fu_1248_p2;
wire   [0:0] tmp3_fu_1242_p2;
wire   [0:0] tmp_i_i6_fu_1260_p2;
wire   [0:0] tmp_1_i_i7_fu_1266_p2;
wire   [0:0] tmp_i1_i_fu_1278_p2;
wire   [0:0] tmp_1_i1_i_fu_1284_p2;
wire   [0:0] p_Result_s_fu_1170_p3;
reg   [22:0] p_Result_65_fu_1296_p4;
wire   [31:0] p_Result_66_fu_1306_p4;
wire   [0:0] ymaggreater_fu_1320_p2;
wire   [0:0] ymaggreater_1_fu_1326_p2;
wire   [0:0] p_Result_17_fu_1196_p3;
wire   [0:0] p_i_fu_1332_p3;
wire   [0:0] ymaggreater2_i_fu_1340_p3;
wire   [0:0] or_cond2_i_fu_1254_p2;
wire   [0:0] tmp_2_demorgan_i_fu_1272_p2;
wire   [0:0] sel_tmp_i_fu_1356_p2;
wire   [0:0] sel_tmp1_i8_fu_1362_p2;
wire   [0:0] tmp_4_demorgan_i_fu_1290_p2;
wire   [0:0] sel_tmp2_i9_fu_1368_p2;
wire   [31:0] res_fu_1316_p1;
wire   [31:0] res_1_fu_1348_p3;
wire   [0:0] sel_tmp6_i1_demorgan_fu_1382_p2;
wire   [0:0] sel_tmp6_i1_fu_1388_p2;
wire   [0:0] sel_tmp7_i_fu_1394_p2;
wire   [31:0] res_2_fu_1374_p3;
wire   [0:0] sel_tmp11_demorgan_i_fu_1408_p2;
wire   [0:0] sel_tmp11_i_fu_1414_p2;
wire   [0:0] sel_tmp12_i_fu_1420_p2;
wire   [31:0] res_3_fu_1400_p3;
wire   [31:0] res_4_fu_1426_p3;
wire   [31:0] p_Val2_5_fu_1446_p1;
wire   [31:0] p_Val2_s_fu_1442_p1;
wire   [0:0] p_Result_59_fu_1450_p3;
wire   [30:0] tmp_10_fu_1458_p1;
wire   [31:0] p_Val2_3_fu_1470_p2;
wire   [0:0] p_Result_3_fu_1476_p3;
wire   [0:0] p_Result_62_fu_1492_p3;
wire   [0:0] sel_tmp1_i_fu_1522_p2;
wire   [0:0] sel_tmp6_demorgan_i_fu_1534_p2;
wire   [0:0] tmp_28tmp_i_fu_1500_p2;
wire   [0:0] sel_tmp6_i_fu_1540_p2;
wire   [0:0] tmp2_fu_1546_p2;
wire   [0:0] sel_tmp8_i_fu_1552_p2;
wire   [31:0] p_Result_63_fu_1506_p3;
wire   [31:0] p_Result_61_fu_1484_p3;
wire   [0:0] sel_tmp2_i_fu_1528_p2;
wire   [31:0] p_Result_60_fu_1462_p3;
wire   [31:0] p_Result_64_fu_1514_p3;
wire   [0:0] or_cond_fu_1566_p2;
wire   [31:0] newSel_fu_1558_p3;
wire   [31:0] newSel1_fu_1572_p3;
wire   [31:0] newSel2_fu_1580_p3;
wire   [31:0] sel_tmp9_i_fu_1588_p1;
wire   [0:0] p_Result_69_fu_1609_p3;
wire   [31:0] p_Val2_6_i_i_i1_i_fu_1616_p2;
wire   [0:0] sel_tmp_i2_fu_1628_p2;
wire   [0:0] sel_tmp2_i2_fu_1639_p2;
wire   [0:0] sel_tmp3_i_fu_1644_p2;
wire   [31:0] p_Val2_41_fu_1621_p3;
wire   [31:0] sel_tmp1_i2_fu_1632_p3;
wire   [31:0] grp_fu_301_p1;
wire   [31:0] p_Val2_42_fu_1670_p1;
wire   [7:0] loc_V_10_fu_1674_p4;
wire   [22:0] loc_V_11_fu_1684_p1;
wire   [0:0] tmp_i_i_fu_1688_p2;
wire   [0:0] tmp_1_i_i_fu_1694_p2;
reg   [1:0] grp_fu_289_opcode;
reg   [4:0] grp_fu_304_opcode;
reg   [4:0] grp_fu_310_opcode;
reg   [26:0] ap_NS_fsm;
reg    ap_condition_72;
reg    ap_condition_150;
reg    ap_condition_179;

// power-on initialization
initial begin
#0 ap_CS_fsm = 27'd1;
end

FCLASS val_out_rd_i_4_FCLASS_fu_281(
    .ap_ready(val_out_rd_i_4_FCLASS_fu_281_ap_ready),
    .val_rs1(val_rs1),
    .val_rs2(val_rs2),
    .ap_return(val_out_rd_i_4_FCLASS_fu_281_ap_return)
);

FPU_faddfsub_32nsbkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
FPU_faddfsub_32nsbkb_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(val_rs1),
    .din1(val_rs2),
    .opcode(grp_fu_289_opcode),
    .ce(1'b1),
    .dout(grp_fu_289_p2)
);

FPU_fmul_32ns_32ncud #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
FPU_fmul_32ns_32ncud_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(val_rs1),
    .din1(val_rs2),
    .ce(1'b1),
    .dout(grp_fu_295_p2)
);

FPU_sitofp_32ns_3dEe #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
FPU_sitofp_32ns_3dEe_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(storemerge_in_i_reg_1800),
    .ce(1'b1),
    .dout(grp_fu_301_p1)
);

FPU_fcmp_32ns_32neOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
FPU_fcmp_32ns_32neOg_U6(
    .din0(grp_fu_304_p0),
    .din1(grp_fu_304_p1),
    .opcode(grp_fu_304_opcode),
    .dout(grp_fu_304_p2)
);

FPU_fcmp_32ns_32neOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
FPU_fcmp_32ns_32neOg_U7(
    .din0(grp_fu_310_p0),
    .din1(grp_fu_310_p1),
    .opcode(grp_fu_310_opcode),
    .dout(grp_fu_310_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (or_cond9_fu_416_p2 == 1'd0) & (tmp_11_fu_404_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (or_cond9_fu_416_p2 == 1'd0) & (tmp_11_fu_404_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (tmp_s_fu_338_p2 == 1'd0))))) begin
        val_out_f_8_reg_164 <= 1'd0;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_4_fu_356_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((tmp_3_fu_350_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0))))) begin
        val_out_f_8_reg_164 <= val_out_f_fu_1592_p2;
    end else if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state9) & (((or_cond_40_reg_1750 == 1'd0) & (tmp_4_reg_1746 == 1'd0) & (tmp_3_reg_1742 == 1'd0) & (or_cond8_reg_1766 == 1'd0) & (or_cond7_reg_1762 == 1'd0) & (or_cond6_reg_1758 == 1'd0) & (or_cond5_reg_1754 == 1'd0) & (tmp_2_reg_1738 == 1'd0) & (tmp_11_reg_1770 == 1'd1) & (tmp_s_reg_1734 == 1'd0)) | ((or_cond_40_reg_1750 == 1'd0) & (tmp_4_reg_1746 == 1'd0) & (or_cond8_reg_1766 == 1'd0) & (or_cond7_reg_1762 == 1'd0) & (or_cond6_reg_1758 == 1'd0) & (or_cond5_reg_1754 == 1'd0) & (tmp_11_reg_1770 == 1'd1) & (tmp_reg_1728 == 1'd0)))))) begin
        val_out_f_8_reg_164 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        val_out_rd_i_9_reg_243 <= val_out_rd_i_9_trunc_fu_1606_p1;
    end else if (((1'b1 == ap_CS_fsm_state9) & (((or_cond_40_reg_1750 == 1'd0) & (tmp_4_reg_1746 == 1'd0) & (tmp_3_reg_1742 == 1'd0) & (or_cond8_reg_1766 == 1'd0) & (or_cond7_reg_1762 == 1'd0) & (or_cond6_reg_1758 == 1'd0) & (or_cond5_reg_1754 == 1'd0) & (tmp_2_reg_1738 == 1'd0) & (tmp_11_reg_1770 == 1'd1) & (tmp_s_reg_1734 == 1'd0)) | ((or_cond_40_reg_1750 == 1'd0) & (tmp_4_reg_1746 == 1'd0) & (or_cond8_reg_1766 == 1'd0) & (or_cond7_reg_1762 == 1'd0) & (or_cond6_reg_1758 == 1'd0) & (or_cond5_reg_1754 == 1'd0) & (tmp_11_reg_1770 == 1'd1) & (tmp_reg_1728 == 1'd0))))) begin
        val_out_rd_i_9_reg_243 <= val_out_rd_i_3_reg_1856;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        val_out_rd_i_9_reg_243 <= val_out_rd_i_2_fu_1707_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        val_out_rd_i_9_reg_243 <= val_out_rd_i_fu_1710_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        val_out_rd_i_9_reg_243 <= val_out_rd_i_1_fu_1713_p1;
    end else if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state17) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (or_cond9_fu_416_p2 == 1'd0) & (tmp_11_fu_404_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (or_cond9_fu_416_p2 == 1'd0) & (tmp_11_fu_404_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (tmp_s_fu_338_p2 == 1'd0)))) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_4_fu_356_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((tmp_3_fu_350_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0)))))) begin
        val_out_rd_i_9_reg_243 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (((or_cond_40_reg_1750 == 1'd0) & (tmp_4_reg_1746 == 1'd0) & (tmp_3_reg_1742 == 1'd0) & (or_cond8_reg_1766 == 1'd0) & (or_cond7_reg_1762 == 1'd0) & (or_cond6_reg_1758 == 1'd0) & (or_cond5_reg_1754 == 1'd0) & (tmp_2_reg_1738 == 1'd0) & (tmp_11_reg_1770 == 1'd1) & (tmp_s_reg_1734 == 1'd0)) | ((or_cond_40_reg_1750 == 1'd0) & (tmp_4_reg_1746 == 1'd0) & (or_cond8_reg_1766 == 1'd0) & (or_cond7_reg_1762 == 1'd0) & (or_cond6_reg_1758 == 1'd0) & (or_cond5_reg_1754 == 1'd0) & (tmp_11_reg_1770 == 1'd1) & (tmp_reg_1728 == 1'd0))))) begin
        x_assign_reg_207 <= val_out_rd_f_6_reg_1861;
    end else if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (or_cond9_fu_416_p2 == 1'd0) & (tmp_11_fu_404_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (or_cond9_fu_416_p2 == 1'd0) & (tmp_11_fu_404_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (tmp_s_fu_338_p2 == 1'd0)))))) begin
        x_assign_reg_207 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        x_assign_reg_207 <= res_13_reg_1826;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        x_assign_reg_207 <= res_12_reg_1831;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_4_fu_356_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((tmp_3_fu_350_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0))))) begin
        x_assign_reg_207 <= val_out_rd_f_3_fu_1598_p3;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        x_assign_reg_207 <= grp_fu_295_p2;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        x_assign_reg_207 <= val_out_rd_f_1_reg_1886;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        x_assign_reg_207 <= val_out_rd_f_reg_1891;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (tmp_s_fu_338_p2 == 1'd0))))) begin
        or_cond5_reg_1754 <= or_cond5_fu_374_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (tmp_s_fu_338_p2 == 1'd0))))) begin
        or_cond6_reg_1758 <= or_cond6_fu_386_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (tmp_s_fu_338_p2 == 1'd0))))) begin
        or_cond7_reg_1762 <= or_cond7_fu_392_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (tmp_s_fu_338_p2 == 1'd0))))) begin
        or_cond8_reg_1766 <= or_cond8_fu_398_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_4_fu_356_p2 == 1'd0) & (tmp_fu_332_p2 == 1'd0)) | ((tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (tmp_s_fu_338_p2 == 1'd0))))) begin
        or_cond_40_reg_1750 <= or_cond_40_fu_368_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_11_fu_404_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (tmp_11_fu_404_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0))))) begin
        or_cond_i_reg_1782 <= or_cond_i_fu_464_p2;
        p_Val2_37_reg_1793 <= p_Val2_37_fu_584_p3;
        p_Val2_38_reg_1788 <= p_Val2_38_fu_470_p1;
        sel_tmp6_i3_reg_1805 <= sel_tmp6_i3_fu_626_p2;
        storemerge_in_i_reg_1800 <= storemerge_in_i_fu_612_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_4_fu_356_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0))))) begin
        res_12_reg_1831 <= res_12_fu_1434_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (or_cond5_fu_374_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (or_cond5_fu_374_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0))))) begin
        res_13_reg_1826 <= res_13_fu_1158_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((sel_tmp6_i3_reg_1805 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        sel_tmp4_i_reg_1851 <= sel_tmp4_i_fu_1649_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (tmp_s_fu_338_p2 == 1'd0))))) begin
        tmp_11_reg_1770 <= tmp_11_fu_404_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0))))) begin
        tmp_25_reg_1816 <= tmp_25_fu_794_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_fu_338_p2 == 1'd0) & (tmp_fu_332_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_2_reg_1738 <= tmp_2_fu_344_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0))))) begin
        tmp_32_reg_1811 <= tmp_32_fu_710_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_fu_344_p2 == 1'd0) & (tmp_s_fu_338_p2 == 1'd0) & (tmp_fu_332_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_3_reg_1742 <= tmp_3_fu_350_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & ((tmp_fu_332_p2 == 1'd0) | ((tmp_3_fu_350_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (tmp_s_fu_338_p2 == 1'd0))))) begin
        tmp_4_reg_1746 <= tmp_4_fu_356_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0))))) begin
        tmp_51_i_reg_1821 <= tmp_51_i_fu_884_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_reg_1728 <= tmp_fu_332_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_332_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_s_reg_1734 <= tmp_s_fu_338_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        val_out_rd_f_1_reg_1886 <= grp_fu_289_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        val_out_rd_f_6_reg_1861 <= val_out_rd_f_6_fu_1663_p3;
        val_out_rd_i_3_reg_1856 <= val_out_rd_i_3_fu_1657_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        val_out_rd_f_reg_1891 <= grp_fu_289_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_11_fu_404_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (or_cond9_fu_416_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (tmp_11_fu_404_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (or_cond9_fu_416_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0))))) begin
        val_out_rd_i_4_reg_1777 <= val_out_rd_i_4_FCLASS_fu_281_ap_return;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        agg_result_b1_ap_vld = 1'b1;
    end else begin
        agg_result_b1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        agg_result_f_ap_vld = 1'b1;
    end else begin
        agg_result_f_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        agg_result_rd_f_ap_vld = 1'b1;
    end else begin
        agg_result_rd_f_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        agg_result_rd_i_ap_vld = 1'b1;
    end else begin
        agg_result_rd_i_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (((or_cond_40_reg_1750 == 1'd0) & (tmp_4_reg_1746 == 1'd0) & (tmp_3_reg_1742 == 1'd0) & (or_cond8_reg_1766 == 1'd0) & (or_cond7_reg_1762 == 1'd0) & (or_cond6_reg_1758 == 1'd0) & (or_cond5_reg_1754 == 1'd0) & (tmp_2_reg_1738 == 1'd0) & (tmp_11_reg_1770 == 1'd1) & (tmp_s_reg_1734 == 1'd0)) | ((or_cond_40_reg_1750 == 1'd0) & (tmp_4_reg_1746 == 1'd0) & (or_cond8_reg_1766 == 1'd0) & (or_cond7_reg_1762 == 1'd0) & (or_cond6_reg_1758 == 1'd0) & (or_cond5_reg_1754 == 1'd0) & (tmp_11_reg_1770 == 1'd1) & (tmp_reg_1728 == 1'd0))))) begin
        ap_phi_mux_val_out_f_8_phi_fu_169_p24 = 1'd1;
    end else begin
        ap_phi_mux_val_out_f_8_phi_fu_169_p24 = val_out_f_8_reg_164;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (((or_cond_40_reg_1750 == 1'd0) & (tmp_4_reg_1746 == 1'd0) & (tmp_3_reg_1742 == 1'd0) & (or_cond8_reg_1766 == 1'd0) & (or_cond7_reg_1762 == 1'd0) & (or_cond6_reg_1758 == 1'd0) & (or_cond5_reg_1754 == 1'd0) & (tmp_2_reg_1738 == 1'd0) & (tmp_11_reg_1770 == 1'd1) & (tmp_s_reg_1734 == 1'd0)) | ((or_cond_40_reg_1750 == 1'd0) & (tmp_4_reg_1746 == 1'd0) & (or_cond8_reg_1766 == 1'd0) & (or_cond7_reg_1762 == 1'd0) & (or_cond6_reg_1758 == 1'd0) & (or_cond5_reg_1754 == 1'd0) & (tmp_11_reg_1770 == 1'd1) & (tmp_reg_1728 == 1'd0))))) begin
        ap_phi_mux_val_out_rd_i_9_phi_fu_247_p24 = val_out_rd_i_3_reg_1856;
    end else begin
        ap_phi_mux_val_out_rd_i_9_phi_fu_247_p24 = val_out_rd_i_9_reg_243;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (((or_cond_40_reg_1750 == 1'd0) & (tmp_4_reg_1746 == 1'd0) & (tmp_3_reg_1742 == 1'd0) & (or_cond8_reg_1766 == 1'd0) & (or_cond7_reg_1762 == 1'd0) & (or_cond6_reg_1758 == 1'd0) & (or_cond5_reg_1754 == 1'd0) & (tmp_2_reg_1738 == 1'd0) & (tmp_11_reg_1770 == 1'd1) & (tmp_s_reg_1734 == 1'd0)) | ((or_cond_40_reg_1750 == 1'd0) & (tmp_4_reg_1746 == 1'd0) & (or_cond8_reg_1766 == 1'd0) & (or_cond7_reg_1762 == 1'd0) & (or_cond6_reg_1758 == 1'd0) & (or_cond5_reg_1754 == 1'd0) & (tmp_11_reg_1770 == 1'd1) & (tmp_reg_1728 == 1'd0))))) begin
        ap_phi_mux_x_assign_phi_fu_211_p24 = val_out_rd_f_6_reg_1861;
    end else begin
        ap_phi_mux_x_assign_phi_fu_211_p24 = x_assign_reg_207;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_72)) begin
        if (((tmp_2_fu_344_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0))) begin
            grp_fu_289_opcode = 2'd1;
        end else if ((tmp_s_fu_338_p2 == 1'd1)) begin
            grp_fu_289_opcode = 2'd0;
        end else begin
            grp_fu_289_opcode = 'bx;
        end
    end else begin
        grp_fu_289_opcode = 'bx;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0))))) begin
        grp_fu_304_opcode = 5'd3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0))))) begin
        grp_fu_304_opcode = 5'd4;
    end else if ((((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0)))) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_11_fu_404_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (tmp_11_fu_404_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0)))))) begin
        grp_fu_304_opcode = 5'd5;
    end else begin
        grp_fu_304_opcode = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0)))) | ((1'b1 == ap_CS_fsm_state1) & (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0)))) | ((1'b1 == ap_CS_fsm_state1) & (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0)))))) begin
        grp_fu_304_p0 = val_rs1;
    end else if (((1'b1 == ap_CS_fsm_state1) & (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_11_fu_404_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (tmp_11_fu_404_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0))))) begin
        grp_fu_304_p0 = val_rs2;
    end else begin
        grp_fu_304_p0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0)))) | ((1'b1 == ap_CS_fsm_state1) & (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0)))) | ((1'b1 == ap_CS_fsm_state1) & (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0)))))) begin
        grp_fu_304_p1 = val_rs2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_11_fu_404_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (tmp_11_fu_404_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0))))) begin
        grp_fu_304_p1 = 32'd1065353216;
    end else begin
        grp_fu_304_p1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((1'b1 == ap_condition_179)) begin
            grp_fu_310_opcode = 5'd5;
        end else if ((1'b1 == ap_condition_150)) begin
            grp_fu_310_opcode = 5'd3;
        end else begin
            grp_fu_310_opcode = 'bx;
        end
    end else begin
        grp_fu_310_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'b1 == ap_condition_179)) begin
            grp_fu_310_p0 = val_rs1;
        end else if ((1'b1 == ap_condition_150)) begin
            grp_fu_310_p0 = val_rs2;
        end else begin
            grp_fu_310_p0 = 'bx;
        end
    end else begin
        grp_fu_310_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'b1 == ap_condition_179)) begin
            grp_fu_310_p1 = val_rs2;
        end else if ((1'b1 == ap_condition_150)) begin
            grp_fu_310_p1 = 32'd1065353216;
        end else begin
            grp_fu_310_p1 = 'bx;
        end
    end else begin
        grp_fu_310_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_4_fu_356_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (or_cond9_fu_416_p2 == 1'd0) & (tmp_11_fu_404_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_fu_332_p2 == 1'd0)) | ((tmp_3_fu_350_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (or_cond9_fu_416_p2 == 1'd0) & (tmp_11_fu_404_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (tmp_s_fu_338_p2 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_11_fu_404_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (or_cond9_fu_416_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (tmp_11_fu_404_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (or_cond9_fu_416_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_11_fu_404_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (tmp_11_fu_404_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (or_cond5_fu_374_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (or_cond5_fu_374_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_4_fu_356_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else if (((tmp_2_fu_344_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0) & (tmp_fu_332_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else if (((tmp_2_fu_344_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0) & (tmp_fu_332_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else if (((tmp_s_fu_338_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign abs_i_fu_604_p3 = ((abscond_i_fu_598_p2[0:0] === 1'b1) ? val_i : neg_i_fu_592_p2);

assign abscond_i_fu_598_p2 = (($signed(val_i) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign agg_result_b1 = (tmp_i_i_fu_1688_p2 & tmp_1_i_i_fu_1694_p2);

assign agg_result_f = ap_phi_mux_val_out_f_8_phi_fu_169_p24;

assign agg_result_rd_f = ap_phi_mux_x_assign_phi_fu_211_p24;

assign agg_result_rd_i = ap_phi_mux_val_out_rd_i_9_phi_fu_247_p24;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_condition_150 = (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_11_fu_404_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (or_cond8_fu_398_p2 == 1'd0) & (or_cond7_fu_392_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (tmp_11_fu_404_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0)));
end

always @ (*) begin
    ap_condition_179 = (((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd1) & (tmp_fu_332_p2 == 1'd0)) | ((or_cond5_fu_374_p2 == 1'd0) & (or_cond_40_fu_368_p2 == 1'd0) & (tmp_4_fu_356_p2 == 1'd0) & (tmp_3_fu_350_p2 == 1'd0) & (tmp_2_fu_344_p2 == 1'd0) & (or_cond6_fu_386_p2 == 1'd1) & (tmp_s_fu_338_p2 == 1'd0)));
end

always @ (*) begin
    ap_condition_72 = ((tmp_fu_332_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1));
end

assign grp_fu_320_p2 = ((val_funct3 == 32'd1) ? 1'b1 : 1'b0);

assign grp_fu_326_p2 = ((val_funct3 == 32'd2) ? 1'b1 : 1'b0);

assign isNeg_fu_512_p3 = sh_assign_fu_506_p2[32'd8];

assign loc_V_10_fu_1674_p4 = {{p_Val2_42_fu_1670_p1[30:23]}};

assign loc_V_11_fu_1684_p1 = p_Val2_42_fu_1670_p1[22:0];

assign loc_V_1_fu_1188_p1 = t_V_5_fu_1166_p1[22:0];

assign loc_V_2_fu_1204_p4 = {{t_V_6_fu_1192_p1[30:23]}};

assign loc_V_3_fu_1214_p1 = t_V_6_fu_1192_p1[22:0];

assign loc_V_4_fu_902_p4 = {{t_V_8_fu_890_p1[30:23]}};

assign loc_V_5_fu_912_p1 = t_V_8_fu_890_p1[22:0];

assign loc_V_6_fu_928_p4 = {{t_V_9_fu_916_p1[30:23]}};

assign loc_V_7_fu_938_p1 = t_V_9_fu_916_p1[22:0];

assign loc_V_8_fu_474_p4 = {{p_Val2_38_fu_470_p1[30:23]}};

assign loc_V_9_fu_484_p1 = p_Val2_38_fu_470_p1[22:0];

assign loc_V_fu_1178_p4 = {{t_V_5_fu_1166_p1[30:23]}};

assign neg_i_fu_592_p2 = (32'd0 - val_i);

assign newSel1_fu_1572_p3 = ((tmp_fu_332_p2[0:0] === 1'b1) ? p_Result_60_fu_1462_p3 : p_Result_64_fu_1514_p3);

assign newSel2_fu_1580_p3 = ((or_cond_fu_1566_p2[0:0] === 1'b1) ? newSel_fu_1558_p3 : newSel1_fu_1572_p3);

assign newSel_fu_1558_p3 = ((sel_tmp8_i_fu_1552_p2[0:0] === 1'b1) ? p_Result_63_fu_1506_p3 : p_Result_61_fu_1484_p3);

assign notlhs1_fu_836_p2 = ((tmp_9_fu_804_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notlhs2_fu_854_p2 = ((tmp_1_fu_822_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notlhs5_fu_752_p2 = ((tmp_19_fu_720_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notlhs6_fu_770_p2 = ((tmp_20_fu_738_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notlhs7_fu_668_p2 = ((tmp_26_fu_636_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notlhs8_fu_686_p2 = ((tmp_27_fu_654_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notlhs_fu_440_p2 = ((tmp_33_fu_426_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notrhs1_fu_842_p2 = ((tmp_53_fu_814_p1 == 23'd0) ? 1'b1 : 1'b0);

assign notrhs2_fu_860_p2 = ((tmp_54_fu_832_p1 == 23'd0) ? 1'b1 : 1'b0);

assign notrhs5_fu_758_p2 = ((tmp_55_fu_730_p1 == 23'd0) ? 1'b1 : 1'b0);

assign notrhs6_fu_776_p2 = ((tmp_56_fu_748_p1 == 23'd0) ? 1'b1 : 1'b0);

assign notrhs7_fu_674_p2 = ((tmp_57_fu_646_p1 == 23'd0) ? 1'b1 : 1'b0);

assign notrhs8_fu_692_p2 = ((tmp_58_fu_664_p1 == 23'd0) ? 1'b1 : 1'b0);

assign notrhs_fu_446_p2 = ((tmp_59_fu_436_p1 == 23'd0) ? 1'b1 : 1'b0);

assign or_cond2_i_fu_1254_p2 = (tmp4_fu_1248_p2 & tmp3_fu_1242_p2);

assign or_cond4_i_fu_978_p2 = (tmp6_fu_972_p2 & tmp5_fu_966_p2);

assign or_cond5_fu_374_p2 = (tmp_5_fu_362_p2 & grp_fu_320_p2);

assign or_cond6_fu_386_p2 = (tmp_8_fu_380_p2 & grp_fu_326_p2);

assign or_cond7_fu_392_p2 = (tmp_8_fu_380_p2 & grp_fu_320_p2);

assign or_cond8_fu_398_p2 = (tmp_fu_332_p2 & tmp_8_fu_380_p2);

assign or_cond9_fu_416_p2 = (tmp_12_fu_410_p2 & grp_fu_320_p2);

assign or_cond_40_fu_368_p2 = (tmp_fu_332_p2 & tmp_5_fu_362_p2);

assign or_cond_fu_1566_p2 = (sel_tmp8_i_fu_1552_p2 | sel_tmp2_i_fu_1528_p2);

assign or_cond_i_fu_464_p2 = (tmp_36_fu_458_p2 & grp_fu_310_p2);

assign p_Result_17_fu_1196_p3 = t_V_6_fu_1192_p1[32'd31];

assign p_Result_36_fu_894_p3 = t_V_8_fu_890_p1[32'd31];

assign p_Result_3_fu_1476_p3 = p_Val2_3_fu_1470_p2[32'd31];

assign p_Result_40_fu_920_p3 = t_V_9_fu_916_p1[32'd31];

assign p_Result_59_fu_1450_p3 = p_Val2_5_fu_1446_p1[32'd31];

assign p_Result_60_fu_1462_p3 = {{p_Result_59_fu_1450_p3}, {tmp_10_fu_1458_p1}};

assign p_Result_61_fu_1484_p3 = {{p_Result_3_fu_1476_p3}, {tmp_10_fu_1458_p1}};

assign p_Result_62_fu_1492_p3 = p_Val2_s_fu_1442_p1[32'd31];

assign p_Result_63_fu_1506_p3 = {{1'd1}, {tmp_10_fu_1458_p1}};

assign p_Result_64_fu_1514_p3 = {{1'd0}, {tmp_10_fu_1458_p1}};

always @ (*) begin
    p_Result_65_fu_1296_p4 = loc_V_1_fu_1188_p1;
    p_Result_65_fu_1296_p4[32'd22] = |(1'd1);
end

assign p_Result_66_fu_1306_p4 = {{{p_Result_s_fu_1170_p3}, {8'd255}}, {p_Result_65_fu_1296_p4}};

always @ (*) begin
    p_Result_67_fu_1020_p4 = loc_V_5_fu_912_p1;
    p_Result_67_fu_1020_p4[32'd22] = |(1'd1);
end

assign p_Result_68_fu_1030_p4 = {{{p_Result_36_fu_894_p3}, {8'd255}}, {p_Result_67_fu_1020_p4}};

assign p_Result_69_fu_1609_p3 = p_Val2_38_reg_1788[32'd31];

assign p_Result_s_fu_1170_p3 = t_V_5_fu_1166_p1[32'd31];

assign p_Val2_37_fu_584_p3 = ((isNeg_fu_512_p3[0:0] === 1'b1) ? tmp_38_fu_570_p1 : tmp_39_fu_574_p4);

assign p_Val2_38_fu_470_p1 = val_rs1;

assign p_Val2_3_fu_1470_p2 = (p_Val2_5_fu_1446_p1 ^ 32'd2147483648);

assign p_Val2_41_fu_1621_p3 = ((p_Result_69_fu_1609_p3[0:0] === 1'b1) ? p_Val2_6_i_i_i1_i_fu_1616_p2 : p_Val2_37_reg_1793);

assign p_Val2_42_fu_1670_p1 = ap_phi_mux_x_assign_phi_fu_211_p24;

assign p_Val2_5_fu_1446_p1 = val_rs2;

assign p_Val2_6_i_i_i1_i_fu_1616_p2 = (32'd0 - p_Val2_37_reg_1793);

assign p_Val2_s_fu_1442_p1 = val_rs1;

assign p_i1_fu_1056_p3 = ((p_Result_36_fu_894_p3[0:0] === 1'b1) ? ymaggreater_3_fu_1050_p2 : ymaggreater_2_fu_1044_p2);

assign p_i_fu_1332_p3 = ((p_Result_s_fu_1170_p3[0:0] === 1'b1) ? ymaggreater_1_fu_1326_p2 : ymaggreater_fu_1320_p2);

assign res_10_fu_1150_p3 = ((sel_tmp12_i1_fu_1144_p2[0:0] === 1'b1) ? val_rs1 : res_9_fu_1124_p3);

assign res_12_fu_1434_p3 = ((or_cond2_i_fu_1254_p2[0:0] === 1'b1) ? val_rs2 : res_4_fu_1426_p3);

assign res_13_fu_1158_p3 = ((or_cond4_i_fu_978_p2[0:0] === 1'b1) ? val_rs2 : res_10_fu_1150_p3);

assign res_1_fu_1348_p3 = ((ymaggreater2_i_fu_1340_p3[0:0] === 1'b1) ? val_rs1 : val_rs2);

assign res_2_fu_1374_p3 = ((sel_tmp2_i9_fu_1368_p2[0:0] === 1'b1) ? res_fu_1316_p1 : res_1_fu_1348_p3);

assign res_3_fu_1400_p3 = ((sel_tmp7_i_fu_1394_p2[0:0] === 1'b1) ? val_rs2 : res_2_fu_1374_p3);

assign res_4_fu_1426_p3 = ((sel_tmp12_i_fu_1420_p2[0:0] === 1'b1) ? val_rs1 : res_3_fu_1400_p3);

assign res_6_fu_1040_p1 = p_Result_68_fu_1030_p4;

assign res_7_fu_1072_p3 = ((ymaggreater4_i_fu_1064_p3[0:0] === 1'b1) ? val_rs2 : val_rs1);

assign res_8_fu_1098_p3 = ((sel_tmp2_i1_fu_1092_p2[0:0] === 1'b1) ? res_6_fu_1040_p1 : res_7_fu_1072_p3);

assign res_9_fu_1124_p3 = ((sel_tmp7_i1_fu_1118_p2[0:0] === 1'b1) ? val_rs2 : res_8_fu_1098_p3);

assign res_fu_1316_p1 = p_Result_66_fu_1306_p4;

assign sel_tmp11_demorgan_i_1_fu_1132_p2 = (tmp_9_demorgan_i_fu_996_p2 | or_cond4_i_fu_978_p2);

assign sel_tmp11_demorgan_i_fu_1408_p2 = (tmp_2_demorgan_i_fu_1272_p2 | or_cond2_i_fu_1254_p2);

assign sel_tmp11_i1_fu_1138_p2 = (sel_tmp11_demorgan_i_1_fu_1132_p2 ^ 1'd1);

assign sel_tmp11_i_fu_1414_p2 = (sel_tmp11_demorgan_i_fu_1408_p2 ^ 1'd1);

assign sel_tmp12_i1_fu_1144_p2 = (tmp_11_demorgan_i_fu_1014_p2 & sel_tmp11_i1_fu_1138_p2);

assign sel_tmp12_i_fu_1420_p2 = (tmp_4_demorgan_i_fu_1290_p2 & sel_tmp11_i_fu_1414_p2);

assign sel_tmp1_i1_fu_1086_p2 = (tmp_9_demorgan_i_fu_996_p2 & sel_tmp_i1_fu_1080_p2);

assign sel_tmp1_i2_fu_1632_p3 = ((sel_tmp_i2_fu_1628_p2[0:0] === 1'b1) ? p_Val2_37_reg_1793 : 32'd0);

assign sel_tmp1_i8_fu_1362_p2 = (tmp_2_demorgan_i_fu_1272_p2 & sel_tmp_i_fu_1356_p2);

assign sel_tmp1_i_fu_1522_p2 = (tmp_fu_332_p2 ^ 1'd1);

assign sel_tmp2_i1_fu_1092_p2 = (tmp_11_demorgan_i_fu_1014_p2 & sel_tmp1_i1_fu_1086_p2);

assign sel_tmp2_i2_fu_1639_p2 = (or_cond_i_reg_1782 ^ 1'd1);

assign sel_tmp2_i9_fu_1368_p2 = (tmp_4_demorgan_i_fu_1290_p2 & sel_tmp1_i8_fu_1362_p2);

assign sel_tmp2_i_fu_1528_p2 = (sel_tmp1_i_fu_1522_p2 & grp_fu_320_p2);

assign sel_tmp3_i_fu_1644_p2 = (tmp_reg_1728 & sel_tmp2_i2_fu_1639_p2);

assign sel_tmp4_i_fu_1649_p3 = ((sel_tmp3_i_fu_1644_p2[0:0] === 1'b1) ? p_Val2_41_fu_1621_p3 : sel_tmp1_i2_fu_1632_p3);

assign sel_tmp5_i_fu_620_p2 = (tmp_fu_332_p2 ^ 1'd1);

assign sel_tmp6_demorgan_i_fu_1534_p2 = (tmp_fu_332_p2 | grp_fu_320_p2);

assign sel_tmp6_i1_demorgan_fu_1382_p2 = (tmp_i1_i_fu_1278_p2 & tmp_1_i1_i_fu_1284_p2);

assign sel_tmp6_i1_fu_1388_p2 = (sel_tmp6_i1_demorgan_fu_1382_p2 ^ 1'd1);

assign sel_tmp6_i2_demorgan_fu_1106_p2 = (tmp_i2_i_fu_1002_p2 & tmp_1_i2_i_fu_1008_p2);

assign sel_tmp6_i2_fu_1112_p2 = (sel_tmp6_i2_demorgan_fu_1106_p2 ^ 1'd1);

assign sel_tmp6_i3_fu_626_p2 = (sel_tmp5_i_fu_620_p2 & grp_fu_320_p2);

assign sel_tmp6_i_fu_1540_p2 = (sel_tmp6_demorgan_i_fu_1534_p2 ^ 1'd1);

assign sel_tmp7_i1_fu_1118_p2 = (sel_tmp6_i2_fu_1112_p2 & sel_tmp1_i1_fu_1086_p2);

assign sel_tmp7_i_fu_1394_p2 = (sel_tmp6_i1_fu_1388_p2 & sel_tmp1_i8_fu_1362_p2);

assign sel_tmp8_i_fu_1552_p2 = (tmp2_fu_1546_p2 & grp_fu_326_p2);

assign sel_tmp9_i_fu_1588_p1 = newSel2_fu_1580_p3;

assign sel_tmp_i1_fu_1080_p2 = (or_cond4_i_fu_978_p2 ^ 1'd1);

assign sel_tmp_i2_fu_1628_p2 = (tmp_reg_1728 & or_cond_i_reg_1782);

assign sel_tmp_i_fu_1356_p2 = (or_cond2_i_fu_1254_p2 ^ 1'd1);

assign sh_assign_1_fu_530_p3 = ((isNeg_fu_512_p3[0:0] === 1'b1) ? tmp_15_i_i_i_i_cast_fu_526_p1 : sh_assign_fu_506_p2);

assign sh_assign_1_i_cast_c_fu_542_p1 = sh_assign_1_fu_530_p3;

assign sh_assign_1_i_cast_fu_538_p1 = sh_assign_1_fu_530_p3;

assign sh_assign_fu_506_p2 = ($signed(9'd385) + $signed(tmp_i_i_i_i_i_cast_fu_502_p1));

assign storemerge_in_i_fu_612_p3 = ((or_cond_i_fu_464_p2[0:0] === 1'b1) ? abs_i_fu_604_p3 : val_i);

assign t_V_5_fu_1166_p1 = val_rs1;

assign t_V_6_fu_1192_p1 = val_rs2;

assign t_V_8_fu_890_p1 = val_rs1;

assign t_V_9_fu_916_p1 = val_rs2;

assign tmp2_fu_1546_p2 = (tmp_28tmp_i_fu_1500_p2 & sel_tmp6_i_fu_1540_p2);

assign tmp3_fu_1242_p2 = (tmp_9_i_fu_1230_p2 & tmp_8_i_fu_1224_p2);

assign tmp4_fu_1248_p2 = (tmp_i5_fu_1236_p2 & tmp_i4_fu_1218_p2);

assign tmp5_fu_966_p2 = (tmp_i_fu_948_p2 & tmp_6_i_fu_954_p2);

assign tmp6_fu_972_p2 = (tmp_i1_41_fu_942_p2 & tmp_7_i_fu_960_p2);

assign tmp_10_fu_1458_p1 = p_Val2_s_fu_1442_p1[30:0];

assign tmp_11_demorgan_i_fu_1014_p2 = (tmp_i2_i_fu_1002_p2 & tmp_1_i2_i_fu_1008_p2);

assign tmp_11_fu_404_p2 = ((val_funct7 == 32'd96) ? 1'b1 : 1'b0);

assign tmp_12_fu_410_p2 = ((val_funct7 == 32'd112) ? 1'b1 : 1'b0);

assign tmp_13_fu_848_p2 = (notrhs1_fu_842_p2 | notlhs1_fu_836_p2);

assign tmp_14_fu_866_p2 = (notrhs2_fu_860_p2 | notlhs2_fu_854_p2);

assign tmp_14_i_i_i_i_cast1_fu_498_p1 = tmp_14_i_i_i_i_fu_488_p4;

assign tmp_14_i_i_i_i_fu_488_p4 = {{{{1'd1}, {loc_V_9_fu_484_p1}}}, {1'd0}};

assign tmp_15_fu_872_p2 = (tmp_14_fu_866_p2 & tmp_13_fu_848_p2);

assign tmp_15_i_i_i_i_cast_fu_526_p1 = $signed(tmp_15_i_i_i_i_fu_520_p2);

assign tmp_15_i_i_i_i_fu_520_p2 = (8'd127 - loc_V_8_fu_474_p4);

assign tmp_16_i_i_i_i_fu_546_p1 = $unsigned(sh_assign_1_i_cast_fu_538_p1);

assign tmp_17_fu_878_p2 = (tmp_15_fu_872_p2 & grp_fu_304_p2);

assign tmp_17_i_i_i_i_fu_550_p2 = tmp_14_i_i_i_i_fu_488_p4 >> sh_assign_1_i_cast_c_fu_542_p1;

assign tmp_18_i_i_i_i_fu_556_p2 = tmp_14_i_i_i_i_cast1_fu_498_p1 << tmp_16_i_i_i_i_fu_546_p1;

assign tmp_19_fu_720_p4 = {{val_rs1_to_int2_fu_716_p1[30:23]}};

assign tmp_1_fu_822_p4 = {{val_rs2_to_int_fu_818_p1[30:23]}};

assign tmp_1_i1_i_fu_1284_p2 = ((loc_V_3_fu_1214_p1 != 23'd0) ? 1'b1 : 1'b0);

assign tmp_1_i2_i_fu_1008_p2 = ((loc_V_7_fu_938_p1 != 23'd0) ? 1'b1 : 1'b0);

assign tmp_1_i_i1_fu_990_p2 = ((loc_V_5_fu_912_p1 != 23'd0) ? 1'b1 : 1'b0);

assign tmp_1_i_i7_fu_1266_p2 = ((loc_V_1_fu_1188_p1 != 23'd0) ? 1'b1 : 1'b0);

assign tmp_1_i_i_fu_1694_p2 = ((loc_V_11_fu_1684_p1 != 23'd0) ? 1'b1 : 1'b0);

assign tmp_20_fu_738_p4 = {{val_rs2_to_int2_fu_734_p1[30:23]}};

assign tmp_21_fu_764_p2 = (notrhs5_fu_758_p2 | notlhs5_fu_752_p2);

assign tmp_22_fu_782_p2 = (notrhs6_fu_776_p2 | notlhs6_fu_770_p2);

assign tmp_23_fu_788_p2 = (tmp_22_fu_782_p2 & tmp_21_fu_764_p2);

assign tmp_25_fu_794_p2 = (tmp_23_fu_788_p2 & grp_fu_304_p2);

assign tmp_26_fu_636_p4 = {{val_rs1_to_int3_fu_632_p1[30:23]}};

assign tmp_27_fu_654_p4 = {{val_rs2_to_int3_fu_650_p1[30:23]}};

assign tmp_28_fu_680_p2 = (notrhs7_fu_674_p2 | notlhs7_fu_668_p2);

assign tmp_28tmp_i_fu_1500_p2 = (p_Result_62_fu_1492_p3 ^ p_Result_59_fu_1450_p3);

assign tmp_29_fu_698_p2 = (notrhs8_fu_692_p2 | notlhs8_fu_686_p2);

assign tmp_2_demorgan_i_fu_1272_p2 = (tmp_i_i6_fu_1260_p2 & tmp_1_i_i7_fu_1266_p2);

assign tmp_2_fu_344_p2 = ((val_funct7 == 32'd4) ? 1'b1 : 1'b0);

assign tmp_30_fu_704_p2 = (tmp_29_fu_698_p2 & tmp_28_fu_680_p2);

assign tmp_32_fu_710_p2 = (tmp_30_fu_704_p2 & grp_fu_304_p2);

assign tmp_33_fu_426_p4 = {{val_rs2_to_int4_fu_422_p1[30:23]}};

assign tmp_34_fu_452_p2 = (notrhs_fu_446_p2 | notlhs_fu_440_p2);

assign tmp_36_fu_458_p2 = (tmp_34_fu_452_p2 & grp_fu_304_p2);

assign tmp_38_fu_570_p1 = tmp_62_fu_562_p3;

assign tmp_39_fu_574_p4 = {{tmp_18_i_i_i_i_fu_556_p2[55:24]}};

assign tmp_3_fu_350_p2 = ((val_funct7 == 32'd8) ? 1'b1 : 1'b0);

assign tmp_4_demorgan_i_fu_1290_p2 = (tmp_i1_i_fu_1278_p2 & tmp_1_i1_i_fu_1284_p2);

assign tmp_4_fu_356_p2 = ((val_funct7 == 32'd16) ? 1'b1 : 1'b0);

assign tmp_51_i_fu_884_p2 = (tmp_17_fu_878_p2 & grp_fu_310_p2);

assign tmp_53_fu_814_p1 = val_rs1_to_int_fu_800_p1[22:0];

assign tmp_54_fu_832_p1 = val_rs2_to_int_fu_818_p1[22:0];

assign tmp_55_fu_730_p1 = val_rs1_to_int2_fu_716_p1[22:0];

assign tmp_56_fu_748_p1 = val_rs2_to_int2_fu_734_p1[22:0];

assign tmp_57_fu_646_p1 = val_rs1_to_int3_fu_632_p1[22:0];

assign tmp_58_fu_664_p1 = val_rs2_to_int3_fu_650_p1[22:0];

assign tmp_59_fu_436_p1 = val_rs2_to_int4_fu_422_p1[22:0];

assign tmp_5_fu_362_p2 = ((val_funct7 == 32'd20) ? 1'b1 : 1'b0);

assign tmp_62_fu_562_p3 = tmp_17_i_i_i_i_fu_550_p2[32'd24];

assign tmp_6_i_fu_954_p2 = ((loc_V_6_fu_928_p4 == 8'd0) ? 1'b1 : 1'b0);

assign tmp_7_i_fu_960_p2 = ((loc_V_7_fu_938_p1 == 23'd0) ? 1'b1 : 1'b0);

assign tmp_8_fu_380_p2 = ((val_funct7 == 32'd80) ? 1'b1 : 1'b0);

assign tmp_8_i_fu_1224_p2 = ((loc_V_1_fu_1188_p1 == 23'd0) ? 1'b1 : 1'b0);

assign tmp_9_demorgan_i_fu_996_p2 = (tmp_i_i1_fu_984_p2 & tmp_1_i_i1_fu_990_p2);

assign tmp_9_fu_804_p4 = {{val_rs1_to_int_fu_800_p1[30:23]}};

assign tmp_9_i_fu_1230_p2 = ((loc_V_2_fu_1204_p4 == 8'd0) ? 1'b1 : 1'b0);

assign tmp_fu_332_p2 = ((val_funct3 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_i1_41_fu_942_p2 = ((loc_V_4_fu_902_p4 == 8'd0) ? 1'b1 : 1'b0);

assign tmp_i1_i_fu_1278_p2 = ((loc_V_2_fu_1204_p4 == 8'd255) ? 1'b1 : 1'b0);

assign tmp_i2_i_fu_1002_p2 = ((loc_V_6_fu_928_p4 == 8'd255) ? 1'b1 : 1'b0);

assign tmp_i4_fu_1218_p2 = ((loc_V_fu_1178_p4 == 8'd0) ? 1'b1 : 1'b0);

assign tmp_i5_fu_1236_p2 = ((loc_V_3_fu_1214_p1 == 23'd0) ? 1'b1 : 1'b0);

assign tmp_i_fu_948_p2 = ((loc_V_5_fu_912_p1 == 23'd0) ? 1'b1 : 1'b0);

assign tmp_i_i1_fu_984_p2 = ((loc_V_4_fu_902_p4 == 8'd255) ? 1'b1 : 1'b0);

assign tmp_i_i6_fu_1260_p2 = ((loc_V_fu_1178_p4 == 8'd255) ? 1'b1 : 1'b0);

assign tmp_i_i_fu_1688_p2 = ((loc_V_10_fu_1674_p4 == 8'd255) ? 1'b1 : 1'b0);

assign tmp_i_i_i_i_i_cast_fu_502_p1 = loc_V_8_fu_474_p4;

assign tmp_s_fu_338_p2 = ((val_funct7 == 32'd0) ? 1'b1 : 1'b0);

assign val_out_f_fu_1592_p2 = (sel_tmp6_demorgan_i_fu_1534_p2 | grp_fu_326_p2);

assign val_out_rd_f_3_fu_1598_p3 = ((val_out_f_fu_1592_p2[0:0] === 1'b1) ? sel_tmp9_i_fu_1588_p1 : 32'd0);

assign val_out_rd_f_6_fu_1663_p3 = ((sel_tmp6_i3_reg_1805[0:0] === 1'b1) ? grp_fu_301_p1 : 32'd0);

assign val_out_rd_i_1_fu_1713_p1 = tmp_51_i_reg_1821;

assign val_out_rd_i_2_fu_1707_p1 = tmp_32_reg_1811;

assign val_out_rd_i_3_fu_1657_p3 = ((sel_tmp6_i3_reg_1805[0:0] === 1'b1) ? 32'd0 : sel_tmp4_i_reg_1851);

assign val_out_rd_i_9_trunc_fu_1606_p1 = val_out_rd_i_4_reg_1777;

assign val_out_rd_i_fu_1710_p1 = tmp_25_reg_1816;

assign val_rs1_to_int2_fu_716_p1 = val_rs1;

assign val_rs1_to_int3_fu_632_p1 = val_rs1;

assign val_rs1_to_int_fu_800_p1 = val_rs1;

assign val_rs2_to_int2_fu_734_p1 = val_rs2;

assign val_rs2_to_int3_fu_650_p1 = val_rs2;

assign val_rs2_to_int4_fu_422_p1 = val_rs2;

assign val_rs2_to_int_fu_818_p1 = val_rs2;

assign ymaggreater2_i_fu_1340_p3 = ((p_Result_17_fu_1196_p3[0:0] === 1'b1) ? p_i_fu_1332_p3 : ymaggreater_fu_1320_p2);

assign ymaggreater4_i_fu_1064_p3 = ((p_Result_40_fu_920_p3[0:0] === 1'b1) ? p_i1_fu_1056_p3 : ymaggreater_2_fu_1044_p2);

assign ymaggreater_1_fu_1326_p2 = (ymaggreater_fu_1320_p2 ^ 1'd1);

assign ymaggreater_2_fu_1044_p2 = (($signed(t_V_8_fu_890_p1) < $signed(t_V_9_fu_916_p1)) ? 1'b1 : 1'b0);

assign ymaggreater_3_fu_1050_p2 = (ymaggreater_2_fu_1044_p2 ^ 1'd1);

assign ymaggreater_fu_1320_p2 = (($signed(t_V_5_fu_1166_p1) < $signed(t_V_6_fu_1192_p1)) ? 1'b1 : 1'b0);

endmodule //FPU
