# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/arty_scr1/arty_scr1.cache/wt [current_project]
set_property parent.project_path D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/arty_scr1/arty_scr1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty:part0:1.1 [current_project]
set_property ip_output_repo d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/arty_scr1/arty_scr1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property verilog_define SCR1_ARCH_CUSTOM=1 [current_fileset]
read_verilog {
  D:/GitHub/scr1-sdk_orig/scr1/src/includes/scr1_arch_description.svh
  D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/src/scr1_arch_custom.svh
  D:/GitHub/scr1-sdk_orig/scr1/src/includes/scr1_arch_types.svh
  D:/GitHub/scr1-sdk_orig/scr1/src/includes/scr1_riscv_isa_decoding.svh
  D:/GitHub/scr1-sdk_orig/scr1/src/includes/scr1_search_ms1.svh
  D:/GitHub/scr1-sdk_orig/scr1/src/includes/scr1_ipic.svh
  D:/GitHub/scr1-sdk_orig/scr1/src/includes/scr1_memif.svh
  D:/GitHub/scr1-sdk_orig/scr1/src/includes/scr1_ahb.svh
  D:/GitHub/scr1-sdk_orig/scr1/src/includes/scr1_tdu.svh
  D:/GitHub/scr1-sdk_orig/scr1/src/includes/scr1_hdu.svh
  D:/GitHub/scr1-sdk_orig/scr1/src/includes/scr1_tapc.svh
  D:/GitHub/scr1-sdk_orig/scr1/src/includes/scr1_dm.svh
  D:/GitHub/scr1-sdk_orig/scr1/src/includes/scr1_csr.svh
}
set_property file_type "Verilog Header" [get_files D:/GitHub/scr1-sdk_orig/scr1/src/includes/scr1_arch_description.svh]
set_property file_type "Verilog Header" [get_files D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/src/scr1_arch_custom.svh]
set_property file_type "Verilog Header" [get_files D:/GitHub/scr1-sdk_orig/scr1/src/includes/scr1_arch_types.svh]
set_property file_type "Verilog Header" [get_files D:/GitHub/scr1-sdk_orig/scr1/src/includes/scr1_riscv_isa_decoding.svh]
set_property file_type "Verilog Header" [get_files D:/GitHub/scr1-sdk_orig/scr1/src/includes/scr1_search_ms1.svh]
set_property file_type "Verilog Header" [get_files D:/GitHub/scr1-sdk_orig/scr1/src/includes/scr1_ipic.svh]
set_property file_type "Verilog Header" [get_files D:/GitHub/scr1-sdk_orig/scr1/src/includes/scr1_memif.svh]
set_property file_type "Verilog Header" [get_files D:/GitHub/scr1-sdk_orig/scr1/src/includes/scr1_ahb.svh]
set_property file_type "Verilog Header" [get_files D:/GitHub/scr1-sdk_orig/scr1/src/includes/scr1_tdu.svh]
set_property file_type "Verilog Header" [get_files D:/GitHub/scr1-sdk_orig/scr1/src/includes/scr1_hdu.svh]
set_property file_type "Verilog Header" [get_files D:/GitHub/scr1-sdk_orig/scr1/src/includes/scr1_tapc.svh]
set_property file_type "Verilog Header" [get_files D:/GitHub/scr1-sdk_orig/scr1/src/includes/scr1_dm.svh]
set_property file_type "Verilog Header" [get_files D:/GitHub/scr1-sdk_orig/scr1/src/includes/scr1_csr.svh]
read_verilog -library xil_defaultlib -sv {
  D:/GitHub/scr1-sdk_orig/scr1/src/pipeline/scr1_pipe_mprf.sv
  D:/GitHub/scr1-sdk_orig/scr1/src/pipeline/scr1_pipe_lsu.sv
  D:/GitHub/scr1-sdk_orig/scr1/src/pipeline/scr1_pipe_ifu.sv
  D:/GitHub/scr1-sdk_orig/scr1/src/pipeline/scr1_pipe_idu.sv
  D:/GitHub/scr1-sdk_orig/scr1/src/pipeline/scr1_pipe_ialu.sv
  D:/GitHub/scr1-sdk_orig/scr1/src/pipeline/scr1_pipe_exu.sv
  D:/GitHub/scr1-sdk_orig/scr1/src/pipeline/scr1_pipe_hdu.sv
  D:/GitHub/scr1-sdk_orig/scr1/src/pipeline/scr1_pipe_csr.sv
  D:/GitHub/scr1-sdk_orig/scr1/src/pipeline/scr1_ipic.sv
  D:/GitHub/scr1-sdk_orig/scr1/src/pipeline/scr1_pipe_tdu.sv
  D:/GitHub/scr1-sdk_orig/scr1/src/pipeline/scr1_pipe_top.sv
  D:/GitHub/scr1-sdk_orig/scr1/src/core/primitives/scr1_reset_cells.sv
  D:/GitHub/scr1-sdk_orig/scr1/src/core/scr1_dm.sv
  D:/GitHub/scr1-sdk_orig/scr1/src/core/scr1_dmi.sv
  D:/GitHub/scr1-sdk_orig/scr1/src/core/scr1_scu.sv
  D:/GitHub/scr1-sdk_orig/scr1/src/core/scr1_tapc_synchronizer.sv
  D:/GitHub/scr1-sdk_orig/scr1/src/core/scr1_tapc_shift_reg.sv
  D:/GitHub/scr1-sdk_orig/scr1/src/core/scr1_tapc.sv
  D:/GitHub/scr1-sdk_orig/scr1/src/core/scr1_core_top.sv
  D:/GitHub/scr1-sdk_orig/scr1/src/top/scr1_dp_memory.sv
  D:/GitHub/scr1-sdk_orig/scr1/src/top/scr1_tcm.sv
  D:/GitHub/scr1-sdk_orig/scr1/src/top/scr1_imem_router.sv
  D:/GitHub/scr1-sdk_orig/scr1/src/top/scr1_imem_ahb.sv
  D:/GitHub/scr1-sdk_orig/scr1/src/top/scr1_dmem_router.sv
  D:/GitHub/scr1-sdk_orig/scr1/src/top/scr1_dmem_ahb.sv
  D:/GitHub/scr1-sdk_orig/scr1/src/top/scr1_timer.sv
  D:/GitHub/scr1-sdk_orig/scr1/src/top/scr1_top_ahb.sv
  D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/src/arty_scr1.sv
}
read_verilog -library xil_defaultlib {
  D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/arty_scr1/arty_scr1.srcs/sources_1/imports/new/testb_fpu.v
  D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/arty_scr1/arty_scr1.srcs/sources_1/FPU_fcmp_32ns_32neOg.v
  D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/arty_scr1/arty_scr1.srcs/sources_1/FPU_faddfsub_32nsbkb.v
  D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/arty_scr1/arty_scr1.srcs/sources_1/FPU_fmul_32ns_32ncud.v
  D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/arty_scr1/arty_scr1.srcs/sources_1/FPU_sitofp_32ns_3dEe.v
  D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/arty_scr1/arty_scr1.srcs/sources_1/FCLASS.v
  D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/arty_scr1/arty_scr1.srcs/sources_1/FPU.v
}
add_files D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/system.bd
set_property used_in_implementation false [get_files -all d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_ahblite_axi_bridge_0_0/system_ahblite_axi_bridge_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_ahblite_axi_bridge_1_0/system_ahblite_axi_bridge_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_axi_bram_ctrl_0_0/system_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_axi_gpio_3_0/system_axi_gpio_3_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_axi_gpio_3_0/system_axi_gpio_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_axi_gpio_3_0/system_axi_gpio_3_0.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_axi_uart16550_0_0/system_axi_uart16550_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_axi_uart16550_0_0/system_axi_uart16550_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_axi_uart16550_0_0/system_axi_uart16550_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_blk_mem_gen_0_0/system_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_jtag_axi_0_0/constraints/jtag_axi.xdc]
set_property used_in_synthesis false [get_files -all d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_jtag_axi_0_0/constraints/system_jtag_axi_0_0_impl.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_jtag_axi_0_0/constraints/system_jtag_axi_0_0_impl.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_jtag_axi_0_0/system_jtag_axi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_auto_pc_2/system_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/system_ooc.xdc]

add_files D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/sys_pll/sys_pll.bd
set_property used_in_implementation false [get_files -all d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/sys_pll/ip/sys_pll_clk_wiz_0_0/sys_pll_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/sys_pll/ip/sys_pll_clk_wiz_0_0/sys_pll_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/sys_pll/ip/sys_pll_clk_wiz_0_0/sys_pll_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/sys_pll/sys_pll_ooc.xdc]

read_ip -quiet D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/arty_scr1/arty_scr1.srcs/sources_1/ip/FPU_ap_faddfsub_3_full_dsp_32/FPU_ap_faddfsub_3_full_dsp_32.xci

read_ip -quiet D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/arty_scr1/arty_scr1.srcs/sources_1/ip/FPU_ap_fcmp_0_no_dsp_32/FPU_ap_fcmp_0_no_dsp_32.xci

read_ip -quiet D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/arty_scr1/arty_scr1.srcs/sources_1/ip/FPU_ap_fmul_2_max_dsp_32/FPU_ap_fmul_2_max_dsp_32.xci

read_ip -quiet D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/arty_scr1/arty_scr1.srcs/sources_1/ip/FPU_ap_sitofp_4_no_dsp_32/FPU_ap_sitofp_4_no_dsp_32.xci

read_ip -quiet d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/arty_scr1/arty_scr1.srcs/sources_1/ip/FPU_ap_faddfsub_0_full_dsp_32/FPU_ap_faddfsub_0_full_dsp_32.xci

read_ip -quiet d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/arty_scr1/arty_scr1.srcs/sources_1/ip/FPU_ap_fmul_0_max_dsp_32/FPU_ap_fmul_0_max_dsp_32.xci

read_ip -quiet d:/GitHub/scr1-sdk_orig/fpga/arty/scr1/arty_scr1/arty_scr1.srcs/sources_1/ip/FPU_ap_sitofp_0_no_dsp_32/FPU_ap_sitofp_0_no_dsp_32.xci

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/constrs/arty_scr1_synth.xdc
set_property used_in_implementation false [get_files D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/constrs/arty_scr1_synth.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top arty_scr1_top -part xc7a35ticsg324-1L -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef arty_scr1_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file arty_scr1_top_utilization_synth.rpt -pb arty_scr1_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
