# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/constrs/arty_scr1_synth.xdc

# Block Designs: D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_ahblite_axi_bridge_0_0/system_ahblite_axi_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ahblite_axi_bridge_0_0 || ORIG_REF_NAME==system_ahblite_axi_bridge_0_0} -quiet] -quiet

# IP: D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_ahblite_axi_bridge_1_0/system_ahblite_axi_bridge_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ahblite_axi_bridge_1_0 || ORIG_REF_NAME==system_ahblite_axi_bridge_1_0} -quiet] -quiet

# IP: D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_axi_bram_ctrl_0_0/system_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_bram_ctrl_0_0 || ORIG_REF_NAME==system_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0} -quiet] -quiet

# IP: D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_1_0 || ORIG_REF_NAME==system_axi_gpio_1_0} -quiet] -quiet

# IP: D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_2_0 || ORIG_REF_NAME==system_axi_gpio_2_0} -quiet] -quiet

# IP: D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_axi_gpio_3_0/system_axi_gpio_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_3_0 || ORIG_REF_NAME==system_axi_gpio_3_0} -quiet] -quiet

# IP: D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_axi_interconnect_0_0/system_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_0 || ORIG_REF_NAME==system_axi_interconnect_0_0} -quiet] -quiet

# IP: D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_axi_uart16550_0_0/system_axi_uart16550_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_uart16550_0_0 || ORIG_REF_NAME==system_axi_uart16550_0_0} -quiet] -quiet

# IP: D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_blk_mem_gen_0_0/system_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_blk_mem_gen_0_0 || ORIG_REF_NAME==system_blk_mem_gen_0_0} -quiet] -quiet

# IP: D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_jtag_axi_0_0/system_jtag_axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_jtag_axi_0_0 || ORIG_REF_NAME==system_jtag_axi_0_0} -quiet] -quiet

# IP: D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_auto_pc_2/system_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_2 || ORIG_REF_NAME==system_auto_pc_2} -quiet] -quiet

# IP: D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_1 || ORIG_REF_NAME==system_auto_pc_1} -quiet] -quiet

# IP: D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# Block Designs: D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/sys_pll/sys_pll.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_pll || ORIG_REF_NAME==sys_pll} -quiet] -quiet

# IP: D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/sys_pll/ip/sys_pll_clk_wiz_0_0/sys_pll_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_pll_clk_wiz_0_0 || ORIG_REF_NAME==sys_pll_clk_wiz_0_0} -quiet] -quiet

# IP: ip/FPU_ap_faddfsub_3_full_dsp_32/FPU_ap_faddfsub_3_full_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FPU_ap_faddfsub_3_full_dsp_32 || ORIG_REF_NAME==FPU_ap_faddfsub_3_full_dsp_32} -quiet] -quiet

# IP: ip/FPU_ap_fcmp_0_no_dsp_32/FPU_ap_fcmp_0_no_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FPU_ap_fcmp_0_no_dsp_32 || ORIG_REF_NAME==FPU_ap_fcmp_0_no_dsp_32} -quiet] -quiet

# IP: ip/FPU_ap_fmul_2_max_dsp_32/FPU_ap_fmul_2_max_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FPU_ap_fmul_2_max_dsp_32 || ORIG_REF_NAME==FPU_ap_fmul_2_max_dsp_32} -quiet] -quiet

# IP: ip/FPU_ap_sitofp_4_no_dsp_32/FPU_ap_sitofp_4_no_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FPU_ap_sitofp_4_no_dsp_32 || ORIG_REF_NAME==FPU_ap_sitofp_4_no_dsp_32} -quiet] -quiet

# IP: ip/FPU_ap_faddfsub_0_full_dsp_32/FPU_ap_faddfsub_0_full_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FPU_ap_faddfsub_0_full_dsp_32 || ORIG_REF_NAME==FPU_ap_faddfsub_0_full_dsp_32} -quiet] -quiet

# IP: ip/FPU_ap_fmul_0_max_dsp_32/FPU_ap_fmul_0_max_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FPU_ap_fmul_0_max_dsp_32 || ORIG_REF_NAME==FPU_ap_fmul_0_max_dsp_32} -quiet] -quiet

# IP: ip/FPU_ap_sitofp_0_no_dsp_32/FPU_ap_sitofp_0_no_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FPU_ap_sitofp_0_no_dsp_32 || ORIG_REF_NAME==FPU_ap_sitofp_0_no_dsp_32} -quiet] -quiet

# XDC: D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/system/system_ooc.xdc

# XDC: D:/GitHub/scr1-sdk_orig/fpga/arty/scr1/bd/sys_pll/sys_pll_ooc.xdc
